### ISSUE TITLE
https://vincent.bernat.ch/en/blog/2018-packaging-driver-debian-dkms - functionality removed from Debian stable

### ISSUE THREAD

**Issue by voltagex** [vincentbernat/www.luffy.cx#41]
Thanks for your article. Unfortunately, it looks like the mkbmdeb functionality was removed sometime after 2022, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1009179 (and the error message produced by dkms 3.0.10 on Debian is not useful)

I am wondering whether it'd be okay to add a note at the top of the article about this.

**Comment by vincentbernat** [comment]
Thanks! I'll update the article shortly. This is a bit unfortunate...
